# CTA CRIME PROJECT BINARY CLASSIFICATION



Taking the dataset and importing the libraries

In [111]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import chi2
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

#TRAIN DATA
dataset = pd.read_csv("incidenttraindata.csv")
#TEST DATA
dataset1= pd.read_csv("incidentaprildata.csv")



In [112]:
dataset.head()

site_id                    cta_sites incident_date   week_day  week_code  \
0       14    Blue Line Belmont Station     1/31/2020     Friday          1   
1        5       61st Street Lower Yard      1/1/2020  Wednesday          2   
2       12    Blue Line Addison Station      1/1/2020  Wednesday          2   
3      143             Skokie Rail Yard      1/2/2020   Thursday          3   
4       15  Blue Line Californa Station      1/2/2020   Thursday          3   

   weekend  holiday incident_time  incident_time_1 time_category  ...  \
0        0        0          3:37                3    late_night  ...   
1        0        1          2:00                2    late_night  ...   
2        0        1          3:00                3    late_night  ...   
3        0        0          3:00                3    late_night  ...   
4        0        0         22:00               22         night  ...   

      moonset Temperature  weather_description  weather_code  Humidity  \
0  No moonset          32             Overcast             1        76   
1       23:58          28               cloudy             2        82   
2       23:58          28               cloudy             2        83   
3  No moonset          43               cloudy             2        76   
4  No moonset          43               cloudy             2        90   

   cloudcover  heatindex  hours_after_sunrise hours_to_sunset incident  
0         100         32                -4.45           14.45        1  
1          30         28                -6.30           15.50        0  
2          28         28                -5.30           14.50        0  
3          74         43                -5.30           14.52        1  
4          64         43                13.70           -4.48        0  

[5 rows x 31 columns]

# FEATURE SELECTION -Wrapper Methods

In [98]:
#Step-Forward and Step-Backward Selection

In [99]:
#TRAIN DATA
fsdata = pd.read_csv("incidenttraindata.csv")
fsdata=fsdata.drop('cta_sites',axis=1)
fsdata=fsdata.drop('incident_date',axis=1)

In [100]:
conda install -c conda-forge mlxtend

Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [101]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import VarianceThreshold


num_colums = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
numerical_columns = list(fsdata.select_dtypes(include=num_colums).columns)
fsdata = fsdata[numerical_columns]
fsdata.shape

train_features, test_features, train_labels, test_labels = train_test_split(
    fsdata.drop(labels=['incident'], axis=1),
    fsdata['incident'],
    test_size=0.2,
    random_state=41)

correlated_features = set()
correlation_matrix = fsdata.corr()
for i in range(len(correlation_matrix .columns)):
    for j in range(i):
        if abs(correlation_matrix.iloc[i, j]) > 0.8:
            colname = correlation_matrix.columns[i]
            correlated_features.add(colname)


train_features.drop(labels=correlated_features, axis=1, inplace=True)
test_features.drop(labels=correlated_features, axis=1, inplace=True)

train_features.shape, test_features.shape

((482, 14), (121, 14))

In [102]:
#step forward

In [103]:
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.metrics import roc_auc_score

from mlxtend.feature_selection import SequentialFeatureSelector

feature_selector = SequentialFeatureSelector(RandomForestClassifier(n_jobs=-1),
           k_features=10,
           forward=True,
           verbose=2,
           scoring='roc_auc',
           cv=4)

features = feature_selector.fit(np.array(train_features.fillna(0)), train_labels)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", Future

C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:2

C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:2

C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
[Parallel(n_jobs=1)]: Done  13 out of  13 | elapsed:   11.2s finished

[2020-05-08 15:50:19] Features: 2/10 -- score: 0.9760174869361616[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarni

C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:2

C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:2

C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:2

C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:2

C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:2

C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:2

C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:2

In [104]:
filtered_features= train_features.columns[list(features.k_feature_idx_)]
filtered_features

Index(['site_id', 'weekend', 'holiday', 'incident_time_1', 'time_code', 'atm',
       'restaurant', 'totalsnow', 'sunhour', 'weather_code'],
      dtype='object')

In [105]:
#step backward feature selection

In [106]:
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.metrics import roc_auc_score
from mlxtend.feature_selection import SequentialFeatureSelector

feature_selector = SequentialFeatureSelector(RandomForestClassifier(n_jobs=-1),
           k_features=10,
           forward=False,
           verbose=2,
           scoring='roc_auc',
           cv=4)

features = feature_selector.fit(np.array(train_features.fillna(0)), train_labels)

C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent 

C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:2

C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:2

C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:2

C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:2

C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:2

In [109]:
filtered_features= train_features.columns[list(features.k_feature_idx_)]
filtered_features

Index(['site_id', 'week_code', 'weekend', 'holiday', 'atm', 'restaurant',
       'avgtemp', 'sunhour', 'weather_code', 'cloudcover'],
      dtype='object')

# FEATURE SELECTION -Filter Methods - Chi2 - SelectKBest

Dropping the  following attributes

cta_sites: As we have assigned site code for each cta 
    
incidate_date:As gievn we need to drop this not a potential feature

In [113]:
#TRAIN DATA
dataset = pd.read_csv("incidenttraindata.csv")
#TEST DATA
dataset1= pd.read_csv("incidentaprildata.csv")


dataset=dataset.drop('cta_sites',axis=1)
dataset=dataset.drop('incident_date',axis=1)
dataset=dataset.drop('incident_time',axis=1)
dataset=dataset.drop('incident_category',axis=1)
dataset=dataset.drop('hours_after_sunrise',axis=1)
dataset=dataset.drop('hours_to_sunset',axis=1)

churn_df=dataset.copy(deep=True)


Encoding all the categorical attributes  to dtype of object such that we can apply chi2 and best features

In [114]:
label_encoder = LabelEncoder()
churn_df['week_day'] = label_encoder.fit_transform(churn_df['week_day'])
churn_df['weather_description'] = label_encoder.fit_transform(churn_df['weather_description'])
churn_df['time_category'] = label_encoder.fit_transform(churn_df['time_category'])
churn_df['sunrise'] = label_encoder.fit_transform(churn_df['sunrise'])
churn_df['sunset'] = label_encoder.fit_transform(churn_df['sunset'])
churn_df['moonrise'] = label_encoder.fit_transform(churn_df['moonrise'])
churn_df['moonset'] = label_encoder.fit_transform(churn_df['moonset'])
churn_df['sunhour'] = label_encoder.fit_transform(churn_df['sunhour'])


In [115]:
X = churn_df.iloc[:,0:27]  #independent columns
y = churn_df.iloc[:,-1]    #target column i.e incident
#apply SelectKBest class to extract top 10 best features
bestfeatures = SelectKBest(score_func=chi2 , k=10)
X=X.astype(str)


In [116]:
X.head()

site_id week_day week_code weekend holiday incident_time_1 time_category  \
0      14        0         1       0       0               3             3   
1       5        6         2       0       1               2             3   
2      12        6         2       0       1               3             3   
3     143        4         3       0       0               3             3   
4      15        4         3       0       0              22             5   

  time_code atm restaurant  ... sunrise moonrise moonset Temperature  \
0         1   0          0  ...      60       11      87          32   
1         1   0          0  ...      74       14      58          28   
2         1   0          0  ...      74       14      58          28   
3         1   0          0  ...      74       16      87          43   
4         2   1          1  ...      74       16      87          43   

  weather_description weather_code Humidity cloudcover heatindex incident  
0                   1            1       76        100        32        1  
1                   4            2       82         30        28        0  
2                   4            2       83         28        28        0  
3                   4            2       76         74        43        1  
4                   4            2       90         64        43        0  

[5 rows x 25 columns]

Value count for each  prediction label

In [117]:
dataset.incident.value_counts()

1    419
0    184
Name: incident, dtype: int64

# Final attributes with all the values 

In [118]:
fit = bestfeatures.fit(X,y)
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(X.columns)
#concat two dataframes for better visualization 
featureScores = pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['Specs','Score']  #naming the dataframe columns


Getting top 10 best features for furthur modelling 

In [119]:
print(featureScores.nlargest(10,'Score'))  #print 10 best feature

              Specs       Score
0           site_id  492.578858
24         incident  184.000000
9        restaurant   72.629590
22       cloudcover   47.656621
16         moonrise   26.067392
21         Humidity   16.489588
6     time_category   13.926279
13          sunhour   13.669272
7         time_code   12.805497
5   incident_time_1   11.494271


Preparing the dataframe including only this features

In [120]:
#Using only these features in our models
data=dataset[['site_id','incident','restaurant','cloudcover','moonrise','Humidity','time_category','sunhour','time_code','incident_time_1']]

In [121]:
data['moonrise'] = label_encoder.fit_transform(data['moonrise'])
#encoding moonrise as it has some time adn categorical values

C:\Users\SHUBHAM\Anaconda\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [122]:
data.head(3)

site_id  incident  restaurant  cloudcover  moonrise  Humidity  \
0       14         1           0         100        11        76   
1        5         0           0          30        14        82   
2       12         0           0          28        14        83   

  time_category  sunhour  time_code  incident_time_1  
0    late_night      5.0          1                3  
1    late_night      8.7          1                2  
2    late_night      8.7          1                3

# Classification Algorithm - K Nearest Neighbour Algorithm 

In [123]:
data_knn=data.copy(deep=True)
data_knn_1=dataset1.copy(deep=True)

Data preprocessing for KNN

In [124]:
dummy2=pd.get_dummies(data_knn['time_category'])
data_knn=pd.concat([data_knn,dummy2],axis=1)
data_knn=data_knn.drop('time_category',axis=1)


In [125]:
dummy_2=pd.get_dummies(data_knn_1['time_category'])
data_knn_1=pd.concat([data_knn_1,dummy_2],axis=1)
data_knn_1=data_knn_1.drop('time_category',axis=1)


In [126]:
data_knn_1['moonrise'] = label_encoder.fit_transform(data_knn_1['moonrise'])

In [127]:
datafinal=data_knn.copy(deep=True)
datafinaltest=data_knn_1.copy(deep=True)


Normalizing the data and prepare it for KNN

In [128]:
# Normalizing 
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
cols_numeric = data_knn.select_dtypes(include=numerics).columns.tolist()
print('Selected numerical columns:\n',cols_numeric) 

# Normalizing test data
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
cols_numeric1 = data_knn_1.select_dtypes(include=numerics).columns.tolist()
print('Selected numerical columns:\n',cols_numeric1) 

Selected numerical columns:
 ['site_id', 'incident', 'restaurant', 'cloudcover', 'moonrise', 'Humidity', 'sunhour', 'time_code', 'incident_time_1']
Selected numerical columns:
 ['restaurant', 'site_id', 'incident_time_1', 'time_code', 'moonrise', 'Humidity', 'cloudcover', 'incident', 'sunhour']


In [129]:
#Using Min-Max Normalization to scale [0, 1]
for col in cols_numeric:
    data_knn[col]=(data_knn[col]-data_knn[col].min())/(data_knn[col].max()-data_knn[col].min())
 #Using Min-Max Normalization to scale [0, 1]
for col in cols_numeric:
    data_knn_1[col]=(data_knn_1[col]-data_knn_1[col].min())/(data_knn_1[col].max()-data_knn_1[col].min())

In [130]:
datafinal.head(10)

site_id  incident  restaurant  cloudcover  moonrise  Humidity  sunhour  \
0       14         1           0         100        11        76      5.0   
1        5         0           0          30        14        82      8.7   
2       12         0           0          28        14        83      8.7   
3      143         1           0          74        16        76      5.2   
4       15         0           1          64        16        90      5.2   
5       27         0           0          63        16        91      5.2   
6      129         1           9          62        19        93      3.4   
7      133         1           5         100        19        74      3.4   
8       11         0           0          65        19        92      3.4   
9       33         0           0         100        19        72      3.4   

   time_code  incident_time_1  afternoon  early_morning  evening  late_night  \
0          1                3          0              0        0           1   
1          1                2          0              0        0           1   
2          1                3          0              0        0           1   
3          1                3          0              0        0           1   
4          2               22          0              0        0           0   
5          2               23          0              0        0           0   
6          2               23          0              0        0           0   
7          1                1          0              0        0           1   
8          3                4          0              1        0           0   
9          4               16          0              0        1           0   

   morning  night  
0        0      0  
1        0      0  
2        0      0  
3        0      0  
4        0      1  
5        0      1  
6        0      1  
7        0      0  
8        0      0  
9        0      0

In [131]:
# Build KNN Model
# N-fold cross Validation 

from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
import matplotlib as mpl
import seaborn as sns

# Building and Evaluating Models
from sklearn import neighbors
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

# KNN requires Label so we need to Pre-Process the Label values

from sklearn import preprocessing
from sklearn.model_selection import cross_val_score

In [132]:
x = data_knn.drop("incident", axis=1)
y = data_knn["incident"]
x_test  = data_knn_1.drop("incident", axis=1).copy()
ytest = data_knn_1['incident']

In [244]:
data_knn.head(10)

site_id  incident  restaurant  cloudcover  moonrise  Humidity   sunhour  \
0  0.086667       1.0        0.00        1.00  0.127907  0.656716  0.195122   
1  0.026667       0.0        0.00        0.30  0.162791  0.746269  0.646341   
2  0.073333       0.0        0.00        0.28  0.162791  0.761194  0.646341   
3  0.946667       1.0        0.00        0.74  0.186047  0.656716  0.219512   
4  0.093333       0.0        0.05        0.64  0.186047  0.865672  0.219512   
5  0.173333       0.0        0.00        0.63  0.186047  0.880597  0.219512   
6  0.853333       1.0        0.45        0.62  0.220930  0.910448  0.000000   
7  0.880000       1.0        0.25        1.00  0.220930  0.626866  0.000000   
8  0.066667       0.0        0.00        0.65  0.220930  0.895522  0.000000   
9  0.213333       0.0        0.00        1.00  0.220930  0.597015  0.000000   

   time_code  incident_time_1  afternoon  early_morning  evening  late_night  \
0        0.0         0.130435          0              0        0           1   
1        0.0         0.086957          0              0        0           1   
2        0.0         0.130435          0              0        0           1   
3        0.0         0.130435          0              0        0           1   
4        0.2         0.956522          0              0        0           0   
5        0.2         1.000000          0              0        0           0   
6        0.2         1.000000          0              0        0           0   
7        0.0         0.043478          0              0        0           1   
8        0.4         0.173913          0              1        0           0   
9        0.6         0.695652          0              0        1           0   

   morning  night  
0        0      0  
1        0      0  
2        0      0  
3        0      0  
4        0      1  
5        0      1  
6        0      1  
7        0      0  
8        0      0  
9        0      0

In [140]:
for k in range(1, 20, 2): 
    clf=neighbors.KNeighborsClassifier(k, weights='uniform')
    acc=cross_val_score(clf, x, y, cv=5, scoring='accuracy').mean()
    print('K =', k, ',accuracy: ',acc)

K = 1 ,accuracy:  0.6569067296340023
K = 3 ,accuracy:  0.666796305298979
K = 5 ,accuracy:  0.6600458365164247
K = 7 ,accuracy:  0.6683380790332661
K = 9 ,accuracy:  0.6683936384471144
K = 11 ,accuracy:  0.6666018473505104
K = 13 ,accuracy:  0.6748940898673519
K = 15 ,accuracy:  0.6731578581845963
K = 17 ,accuracy:  0.6631849433988471
K = 19 ,accuracy:  0.6582262657128968


In [141]:
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
predictions = cross_val_predict(clf, x, y, cv=5)
from sklearn.metrics import precision_score, recall_score

#confusion_matrix(y, predictions)
print("Precision:", precision_score(y, predictions))
print("Recall:",recall_score(y, predictions))

Precision: 0.7036328871892925
Recall: 0.8782816229116945


Following are accuracy for each label

In [142]:
from sklearn.metrics import precision_recall_fscore_support

precision_recall_fscore_support(y, predictions, average=None,labels=[0])


(array([0.3625]),
 array([0.1576087]),
 array([0.21969697]),
 array([184], dtype=int64))

In [143]:
from sklearn.metrics import precision_recall_fscore_support

precision_recall_fscore_support(y, predictions, average=None,labels=[1])

(array([0.70363289]),
 array([0.87828162]),
 array([0.78131635]),
 array([419], dtype=int64))

Below getting the predicted values for the test data 

In [145]:
clf.fit(x,y)

y_pred=clf.predict(x_test)

y_pred

array([1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1.,
       1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1.,
       1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.])

In [152]:
#overall situation Accuracy on test data

In [147]:
from sklearn.metrics import precision_recall_fscore_support

precision_recall_fscore_support(ytest, y_pred, average=None,labels=[1])

(array([0.86764706]),
 array([0.83098592]),
 array([0.84892086]),
 array([71], dtype=int64))

In [149]:
from sklearn.metrics import precision_recall_fscore_support

precision_recall_fscore_support(ytest, y_pred, average=None,labels=[0])

(array([0.07692308]),
 array([0.1]),
 array([0.08695652]),
 array([10], dtype=int64))

In [151]:
from sklearn.metrics import accuracy_score
accuracy_score(ytest, y_pred, normalize=False)

60

# Decision Tree

In [267]:
# . Decision Trees
# Preprocessing: 1)Encoding the labels; 2)Convert Numerical to Categorical
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix

x = datafinal.drop("incident", axis=1)
y = datafinal["incident"]
x_test  = datafinaltest.drop("incident", axis=1).copy()
y_test = datafinaltest['incident']



# N-fold cross Evaluation
tree = DecisionTreeClassifier(criterion='entropy')
acc=cross_val_score(tree, x, y, cv=5, scoring='accuracy').mean()
print("Tree Accuracy by N-fold Cross Validation:",acc)


predictions = cross_val_predict(tree, x, y, cv=5)
#confusion_matrix(y, predictions)
from sklearn.metrics import precision_score, recall_score

print("Precision tree:", precision_score(y, predictions))
print("Recall tree:",recall_score(y, predictions))



Tree Accuracy by N-fold Cross Validation: 0.8475363526905622
Precision tree: 0.8824884792626728
Recall tree: 0.9140811455847255


In [268]:
from sklearn.metrics import precision_recall_fscore_support

precision_recall_fscore_support(y, predictions, average=None,labels=[0])


(array([0.78698225]),
 array([0.72282609]),
 array([0.75354108]),
 array([184], dtype=int64))

Accuracy for each label data 0 and 1 

In [269]:
from sklearn.metrics import precision_recall_fscore_support

precision_recall_fscore_support(y, predictions, average=None,labels=[1])


(array([0.88248848]),
 array([0.91408115]),
 array([0.89800703]),
 array([419], dtype=int64))

Predicted value for this model on test data

In [286]:
tree.fit(x,y)

y_pred=tree.predict(x_test)

y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [ ]:
#overall situation Accuracy on test data

In [162]:
from sklearn.metrics import precision_recall_fscore_support

precision_recall_fscore_support(y_test, y_pred, average=None,labels=[1])


(array([0.87654321]),
 array([1.]),
 array([0.93421053]),
 array([71], dtype=int64))

In [161]:
from sklearn.metrics import precision_recall_fscore_support

precision_recall_fscore_support(y_test, y_pred, average=None,labels=[0])


C:\Users\SHUBHAM\Anaconda\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


(array([0.]), array([0.]), array([0.]), array([10], dtype=int64))

In [160]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred, normalize=False)

71

# Bagged Decision Tree- Random Forest

In [44]:
bag = BaggingClassifier(tree, n_estimators=100, max_samples=0.8, random_state=1)
acc=cross_val_score(bag, x, y, cv=5, scoring='accuracy').mean()
print("RandomForest Accuracy by N-fold Cross Validation:",acc)
predictions = cross_val_predict(bag, x, y, cv=5)
confusion_matrix(y, predictions)


print("Precision Random Forest:", precision_score(y, predictions))
print("Recall Random Forest:",recall_score(y, predictions))

RandomForest Accuracy by N-fold Cross Validation: 0.8690603514132926
Precision Random Forest: 0.8899082568807339
Recall Random Forest: 0.9260143198090692


Accuracy for Each label data

In [45]:
from sklearn.metrics import precision_recall_fscore_support

precision_recall_fscore_support(y, predictions, average=None,labels=[0])


(array([0.81437126]),
 array([0.73913043]),
 array([0.77492877]),
 array([184], dtype=int64))

In [46]:
from sklearn.metrics import precision_recall_fscore_support

precision_recall_fscore_support(y, predictions, average=None,labels=[1])


(array([0.88990826]),
 array([0.92601432]),
 array([0.90760234]),
 array([419], dtype=int64))

getting the predicted value on test data 

In [189]:
bag.fit(x,y)

y_pred=bag.predict(x_test)

y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [181]:
#overall situation Accuracy on test data

In [164]:
from sklearn.metrics import precision_recall_fscore_support

precision_recall_fscore_support(y_test, y_pred, average=None,labels=[1])


(array([0.87654321]),
 array([1.]),
 array([0.93421053]),
 array([71], dtype=int64))

In [166]:
from sklearn.metrics import precision_recall_fscore_support

precision_recall_fscore_support(y_test, y_pred, average=None,labels=[0])


(array([0.]), array([0.]), array([0.]), array([10], dtype=int64))

In [163]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred, normalize=False)

71

# Bagging algorithm

In [167]:
import pandas
from sklearn import model_selection
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier



X = datafinal.drop(['incident'], axis=1)
Y = datafinal['incident']
x_test=datafinaltest.drop(['incident'], axis=1)
ytest = datafinaltest['incident']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3)

seed = 7
num_trees = 100
max_features = 3
kfold = model_selection.KFold(n_splits=5, random_state=seed)

cart=DecisionTreeClassifier()
model_DT = BaggingClassifier(cart,n_estimators=num_trees, max_features=max_features)
results = model_selection.cross_val_score(model_DT, X, Y, cv=kfold)
predictions = cross_val_predict(model_DT, x, y, cv=5)

pred=results.mean()
print(pred)

0.7628236914600551


In [168]:
from sklearn.metrics import precision_recall_fscore_support

precision_recall_fscore_support(Y, predictions, average=None,labels=[0])


(array([0.83333333]),
 array([0.32608696]),
 array([0.46875]),
 array([184], dtype=int64))

In [169]:
from sklearn.metrics import precision_recall_fscore_support

precision_recall_fscore_support(Y, predictions, average=None,labels=[1])


(array([0.76647834]),
 array([0.97136038]),
 array([0.85684211]),
 array([419], dtype=int64))

In [170]:
model_DT.fit(X,Y)

y_pred=model_DT.predict(x_test)

y_pred

array([1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1], dtype=int64)

In [171]:
ytest.values

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [ ]:
#overall situation Accuracy on test data

In [172]:
from sklearn.metrics import precision_recall_fscore_support

precision_recall_fscore_support(ytest, y_pred, average=None,labels=[1])


(array([0.88095238]),
 array([0.52112676]),
 array([0.65486726]),
 array([71], dtype=int64))

In [173]:
from sklearn.metrics import precision_recall_fscore_support

precision_recall_fscore_support(ytest, y_pred, average=None,labels=[0])


(array([0.12820513]),
 array([0.5]),
 array([0.20408163]),
 array([10], dtype=int64))

In [174]:
from sklearn.metrics import accuracy_score
accuracy_score(ytest, y_pred, normalize=False)

42

# Random forest 

In [175]:
import pandas
from sklearn import model_selection
from sklearn.ensemble import RandomForestClassifier

seed = 7
num_trees = 100
max_features = 3
kfold = model_selection.KFold(n_splits=5, random_state=seed)
model_RF = RandomForestClassifier(n_estimators=num_trees, max_features=max_features)
results = model_selection.cross_val_score(model_RF, X, Y, cv=kfold)
print(results.mean())

confusion_matrix(Y, predictions)
from sklearn.metrics import precision_score, recall_score
predictions = cross_val_predict(model_RF, x, y, cv=5)

print("Precision:", precision_score(Y, predictions))
print("Recall:",recall_score(Y, predictions))

0.7910330578512397
Precision: 0.8207964601769911
Recall: 0.8854415274463007


accuracy for each lable 1 and 0 

In [176]:
from sklearn.metrics import precision_recall_fscore_support

precision_recall_fscore_support(Y, predictions, average=None,labels=[0])


(array([0.68211921]),
 array([0.55978261]),
 array([0.61492537]),
 array([184], dtype=int64))

In [177]:
from sklearn.metrics import precision_recall_fscore_support

precision_recall_fscore_support(Y, predictions, average=None,labels=[1])

(array([0.82079646]),
 array([0.88544153]),
 array([0.85189437]),
 array([419], dtype=int64))

In [252]:
model_RF.fit(X,Y)

y_pred=model_RF.predict(x_test)

y_pred

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [ ]:
#overall situation Accuracy on test data

In [207]:
from sklearn.metrics import precision_recall_fscore_support

precision_recall_fscore_support(ytest, y_pred, average=None,labels=[1])

(array([0.87654321]),
 array([1.]),
 array([0.93421053]),
 array([71], dtype=int64))

In [208]:
from sklearn.metrics import precision_recall_fscore_support

precision_recall_fscore_support(ytest, y_pred, average=None,labels=[1])

(array([0.87654321]),
 array([1.]),
 array([0.93421053]),
 array([71], dtype=int64))

In [209]:
from sklearn.metrics import accuracy_score
accuracy_score(ytest, y_pred, normalize=False)

71

# Extra tree Classifier

In [220]:
from sklearn import model_selection
from sklearn.ensemble import ExtraTreesClassifier

In [221]:
seed = 7
num_trees = 100
max_features = 7
kfold = model_selection.KFold(n_splits=5, random_state=seed)
model_ET = ExtraTreesClassifier(n_estimators=num_trees, max_features=max_features)
results = model_selection.cross_val_score(model_ET, X, Y, cv=kfold)
print(results.mean())

predictions = cross_val_predict(model_ET, X, Y, cv=5)
confusion_matrix(Y, predictions)
from sklearn.metrics import precision_score, recall_score

print("Precision:", precision_score(Y, predictions))
print("Recall:",recall_score(Y, predictions))


0.754504132231405
Precision: 0.8042553191489362
Recall: 0.9021479713603818


Accuracy matrix for each lable 

In [222]:
from sklearn.metrics import precision_recall_fscore_support

precision_recall_fscore_support(Y, predictions, average=None,labels=[0])


(array([0.69172932]),
 array([0.5]),
 array([0.58044164]),
 array([184], dtype=int64))

In [223]:
from sklearn.metrics import precision_recall_fscore_support

precision_recall_fscore_support(Y, predictions, average=None,labels=[1])


(array([0.80425532]),
 array([0.90214797]),
 array([0.8503937]),
 array([419], dtype=int64))

In [224]:
model_ET.fit(X,Y)

y_pred=model_ET.predict(x_test)

y_pred

array([1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [225]:
#overall situation Accuracy on test data

from sklearn.metrics import accuracy_score
accuracy_score(ytest, y_pred, normalize=False)

65

In [226]:
from sklearn.metrics import precision_recall_fscore_support

precision_recall_fscore_support(ytest, y_pred, average=None,labels=[0])


(array([0.]), array([0.]), array([0.]), array([10], dtype=int64))

In [227]:

from sklearn.metrics import precision_recall_fscore_support

precision_recall_fscore_support(ytest, y_pred, average=None,labels=[1])


(array([0.86666667]),
 array([0.91549296]),
 array([0.89041096]),
 array([71], dtype=int64))

# Adaboost Algorithm

In [228]:

X = datafinal.drop(['incident'], axis=1)
Y = datafinal['incident']
x_test=datafinaltest.drop(['incident'], axis=1)
ytest = datafinaltest['incident']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3)

from sklearn import model_selection
from sklearn.ensemble import AdaBoostClassifier
seed = 7
num_trees = 30
kfold = model_selection.KFold(n_splits=5, random_state=seed)
model_AB = AdaBoostClassifier(n_estimators=num_trees, random_state=seed)
results = model_selection.cross_val_score(model_AB, X, Y, cv=kfold)
print("Accuracy:",results.mean())

predictions = cross_val_predict(model_AB, X, Y, cv=5)
confusion_matrix(Y, predictions)
from sklearn.metrics import precision_score, recall_score

print("Precision:", precision_score(Y, predictions))
print("Recall:",recall_score(Y, predictions))

Accuracy: 0.8209228650137741
Precision: 0.8925
Recall: 0.8520286396181385


Accuracy for each lable 0 and 1 

In [229]:
from sklearn.metrics import precision_recall_fscore_support

precision_recall_fscore_support(Y, predictions, average=None,labels=[0])


(array([0.69458128]),
 array([0.76630435]),
 array([0.72868217]),
 array([184], dtype=int64))

In [230]:
from sklearn.metrics import precision_recall_fscore_support

precision_recall_fscore_support(Y, predictions, average=None,labels=[1])


(array([0.8925]),
 array([0.85202864]),
 array([0.87179487]),
 array([419], dtype=int64))

Getting the prediction value for test data

In [231]:
model_AB.fit(X,Y)

y_pred=model_AB.predict(x_test)

y_pred

array([1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1], dtype=int64)

In [232]:
#overall situation Accuracy on test data

from sklearn.metrics import accuracy_score
accuracy_score(ytest, y_pred, normalize=False)

63

In [233]:
from sklearn.metrics import precision_recall_fscore_support

precision_recall_fscore_support(ytest, y_pred, average=None,labels=[0])


(array([0.25]), array([0.4]), array([0.30769231]), array([10], dtype=int64))

In [234]:
from sklearn.metrics import precision_recall_fscore_support

precision_recall_fscore_support(ytest, y_pred, average=None,labels=[1])


(array([0.90769231]),
 array([0.83098592]),
 array([0.86764706]),
 array([71], dtype=int64))

# Stochastic Gradient boosting algortihm

In [235]:
from sklearn import model_selection
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import precision_score, recall_score

In [236]:
seed = 10
num_trees = 50
kfold = model_selection.KFold(n_splits=5, random_state=seed)
model_SG = GradientBoostingClassifier(n_estimators=num_trees, random_state=seed)
results = model_selection.cross_val_score(model_SG, X, Y, cv=kfold)
print("Accuracy:",results.mean())
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
predictions = cross_val_predict(model_SG, X, Y, cv=5)
mat=confusion_matrix(Y, predictions)


print("Precision:", precision_score(Y, predictions))
print("Recall:",recall_score(Y, predictions))
print(mat)

Accuracy: 0.8656611570247934
Precision: 0.8995215311004785
Recall: 0.8973747016706444
[[142  42]
 [ 43 376]]


Accuracy for each label

In [237]:
from sklearn.metrics import precision_recall_fscore_support

precision_recall_fscore_support(Y, predictions, average=None,labels=[0])


(array([0.76756757]),
 array([0.77173913]),
 array([0.7696477]),
 array([184], dtype=int64))

In [238]:

precision_recall_fscore_support(Y, predictions, average=None,labels=[1])


(array([0.89952153]),
 array([0.8973747]),
 array([0.89844683]),
 array([419], dtype=int64))

In [239]:
model_SG.fit(X,Y)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=50,
                           n_iter_no_change=None, presort='auto',
                           random_state=10, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [240]:
y_pred=model_SG.predict(x_test)
y_pred

array([1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1], dtype=int64)

In [241]:
#overall situation Accuracy on test data

from sklearn.metrics import accuracy_score
accuracy_score(ytest, y_pred, normalize=False)

37

In [242]:
from sklearn.metrics import precision_recall_fscore_support

precision_recall_fscore_support(ytest, y_pred, average=None,labels=[0])


(array([0.13043478]),
 array([0.6]),
 array([0.21428571]),
 array([10], dtype=int64))

In [243]:
from sklearn.metrics import precision_recall_fscore_support

precision_recall_fscore_support(ytest, y_pred, average=None,labels=[1])


(array([0.88571429]),
 array([0.43661972]),
 array([0.58490566]),
 array([71], dtype=int64))

# Association Rules

In [79]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
from mlxtend.preprocessing import TransactionEncoder
import matplotlib.pyplot as plt  

In [80]:
data_asso = pd.read_csv('incidenttraindata.csv')

In [81]:
data_asso=data_asso.drop('moonrise',axis=1)
data_asso=data_asso.drop('moonset',axis=1)
data_asso=data_asso.drop('sunset',axis=1)
data_asso=data_asso.drop('sunrise',axis=1)
data_asso=data_asso.drop('cta_sites',axis=1)
data_asso=data_asso.drop('incident_date',axis=1)
data_asso=data_asso.drop('incident_time',axis=1)
data_asso=data_asso.drop('incident_category',axis=1)
data_asso=data_asso.drop('week_code',axis=1)
data_asso=data_asso.drop('time_code',axis=1)
data_asso=data_asso.drop('weather_code',axis=1)
data_asso=data_asso.drop('incident_time_1',axis=1)


In [82]:
data_asso.dtypes

site_id                  int64
week_day                object
weekend                  int64
holiday                  int64
time_category           object
atm                      int64
restaurant               int64
avgtemp                  int64
maxtemp                  int64
totalsnow              float64
sunhour                float64
Temperature              int64
weather_description     object
Humidity                 int64
cloudcover               int64
heatindex                int64
hours_after_sunrise    float64
hours_to_sunset        float64
incident                 int64
dtype: object

Converting the data into string and object 

In [83]:
data_asso['site_id'] = pd.cut(data_asso['site_id'],30)
data_asso['avgtemp'] = pd.cut(data_asso['avgtemp'],3)
data_asso['maxtemp'] = pd.cut(data_asso['maxtemp'],3)
data_asso['totalsnow'] = pd.cut(data_asso['totalsnow'],2)
data_asso['sunhour'] = pd.cut(data_asso['sunhour'],3)
data_asso['Temperature'] = pd.cut(data_asso['Temperature'],6)
data_asso['Humidity'] = pd.cut(data_asso['Humidity'],2)
data_asso['cloudcover'] = pd.cut(data_asso['cloudcover'],2)
data_asso['heatindex'] = pd.cut(data_asso['heatindex'],2)
data_asso['hours_after_sunrise'] = pd.cut(data_asso['hours_after_sunrise'],3)
data_asso['hours_to_sunset'] = pd.cut(data_asso['hours_to_sunset'],3)

In [84]:
print(data_asso.dtypes)

site_id                category
week_day                 object
weekend                   int64
holiday                   int64
time_category            object
atm                       int64
restaurant                int64
avgtemp                category
maxtemp                category
totalsnow              category
sunhour                category
Temperature            category
weather_description      object
Humidity               category
cloudcover             category
heatindex              category
hours_after_sunrise    category
hours_to_sunset        category
incident                  int64
dtype: object


In [85]:
print(data_asso.head())

          site_id   week_day  weekend  holiday time_category  atm  restaurant  \
0    (11.0, 16.0]     Friday        0        0    late_night    0           0   
1     (0.85, 6.0]  Wednesday        0        1    late_night    0           0   
2    (11.0, 16.0]  Wednesday        0        1    late_night    0           0   
3  (141.0, 146.0]   Thursday        0        0    late_night    0           0   
4    (11.0, 16.0]   Thursday        0        0         night    1           1   

            avgtemp           maxtemp         totalsnow         sunhour  \
0  (23.333, 37.667]  (27.667, 41.333]  (-0.00346, 1.73]  (3.392, 6.133]   
1  (23.333, 37.667]  (27.667, 41.333]  (-0.00346, 1.73]  (6.133, 8.867]   
2  (23.333, 37.667]  (27.667, 41.333]  (-0.00346, 1.73]  (6.133, 8.867]   
3    (37.667, 52.0]    (41.333, 55.0]  (-0.00346, 1.73]  (3.392, 6.133]   
4    (37.667, 52.0]    (41.333, 55.0]  (-0.00346, 1.73]  (3.392, 6.133]   

        Temperature weather_description      Humidity     clou

In [86]:
data_asso['site_id'] = 'site_id=' + data_asso['site_id'].astype(str)
data_asso['restaurant'] = 'restaurant=' + data_asso['restaurant'].astype(str)
data_asso['totalsnow'] = 'totalsnow' + data_asso['totalsnow'].astype(str)
data_asso['sunhour'] = 'sunhour=' + data_asso['sunhour'].astype(str)
data_asso['Humidity'] = 'Humidity' + data_asso['Humidity'].astype(str)
data_asso['cloudcover'] = 'cloudcover' + data_asso['cloudcover'].astype(str)
data_asso['hours_after_sunrise'] = 'hours_after_sunrise=' + data_asso['hours_after_sunrise'].astype(str)
data_asso['hours_to_sunset'] = 'hours_to_sunset' + data_asso['hours_to_sunset'].astype(str)
data_asso['weekend'] = 'weekend=' + data_asso['weekend'].astype(str)
data_asso['holiday'] = 'holiday' + data_asso['holiday'].astype(str)
data_asso['atm'] = 'atm' + data_asso['atm'].astype(str)
data_asso['avgtemp'] = 'avgtemp' + data_asso['avgtemp'].astype(str)
data_asso['maxtemp'] = 'maxtemp=' + data_asso['maxtemp'].astype(str)
data_asso['Temperature'] = 'Temperature' + data_asso['Temperature'].astype(str)
data_asso['heatindex'] = 'heatindex' + data_asso['heatindex'].astype(str)
data_asso['incident'] = 'incident=' + data_asso['incident'].astype(str)


Converted all the variable to object

In [87]:
print(data_asso.dtypes)

site_id                object
week_day               object
weekend                object
holiday                object
time_category          object
atm                    object
restaurant             object
avgtemp                object
maxtemp                object
totalsnow              object
sunhour                object
Temperature            object
weather_description    object
Humidity               object
cloudcover             object
heatindex              object
hours_after_sunrise    object
hours_to_sunset        object
incident               object
dtype: object


# convert data frame to lists

Covert  dataframe to list is needed form for asociation rules to apply

# RULES

In [88]:
df_arr = data_asso.stack().groupby(level=0).apply(list).tolist()

In [89]:
#Rules
import numpy as np
import scipy as sp
import pandas as pd
from IPython.display import display, HTML

# Encode lists to transactions
te = TransactionEncoder()
df_transactions = te.fit_transform(df_arr)
# covnert the values to booleans: TRUE and FALSE
df_rules = pd.DataFrame(df_transactions,columns=te.columns_)
display('Data Example',HTML(df_rules.head(5).to_html()))


frequent_itemsets = apriori(df_rules, min_support=0.50, use_colnames=True)
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=0.5)
display('Rules',HTML(rules.to_html()))

'Data Example'

'Rules'

# Getting all the rules having incident on the consequent Part

In [90]:
incident=rules[rules['consequents'] == {'incident=1'}]

In [91]:
incident

antecedents   consequents  \
9                               (Humidity(65.5, 99.0])  (incident=1)   
37                                          (holiday0)  (incident=1)   
45                         (totalsnow(-0.00346, 1.73])  (incident=1)   
47                                         (weekend=0)  (incident=1)   
84                    (Humidity(65.5, 99.0], holiday0)  (incident=1)   
108  (Humidity(65.5, 99.0], totalsnow(-0.00346, 1.73])  (incident=1)   
162              (totalsnow(-0.00346, 1.73], holiday0)  (incident=1)   
168                              (weekend=0, holiday0)  (incident=1)   
186             (weekend=0, totalsnow(-0.00346, 1.73])  (incident=1)   
221  (Humidity(65.5, 99.0], totalsnow(-0.00346, 1.7...  (incident=1)   
263   (weekend=0, totalsnow(-0.00346, 1.73], holiday0)  (incident=1)   

     antecedent support  consequent support   support  confidence      lift  \
9              0.794362            0.694859  0.565506    0.711900  1.024524   
37             0.973466            0.694859  0.678275    0.696763  1.002740   
45             0.938640            0.694859  0.648425    0.690813  0.994177   
47             0.762852            0.694859  0.548922    0.719565  1.035556   
84             0.767828            0.694859  0.548922    0.714903  1.028846   
108            0.733002            0.694859  0.519071    0.708145  1.019120   
162            0.912106            0.694859  0.631841    0.692727  0.996932   
168            0.736318            0.694859  0.532338    0.722973  1.040460   
186            0.729685            0.694859  0.524046    0.718182  1.033565   
221            0.706468            0.694859  0.502488    0.711268  1.023614   
263            0.703151            0.694859  0.507463    0.721698  1.038625   

     leverage  conviction  
9    0.013537    1.059149  
37   0.001854    1.006279  
45  -0.003798    0.986913  
47   0.018847    1.088100  
84   0.015390    1.070305  
108  0.009738    1.045522  
162 -0.001944    0.993062  
168  0.020701    1.101484  
186  0.017018    1.082758  
221  0.011592    1.056830  
263  0.018872    1.096439

Ranking all the rules according to the confidence criteria

In [246]:
incident.sort_values('lift', ascending=False).head(20)

antecedents   consequents  \
168                              (weekend=0, holiday0)  (incident=1)   
263   (weekend=0, totalsnow(-0.00346, 1.73], holiday0)  (incident=1)   
47                                         (weekend=0)  (incident=1)   
186             (weekend=0, totalsnow(-0.00346, 1.73])  (incident=1)   
84                    (Humidity(65.5, 99.0], holiday0)  (incident=1)   
9                               (Humidity(65.5, 99.0])  (incident=1)   
221  (Humidity(65.5, 99.0], totalsnow(-0.00346, 1.7...  (incident=1)   
108  (Humidity(65.5, 99.0], totalsnow(-0.00346, 1.73])  (incident=1)   
37                                          (holiday0)  (incident=1)   
162              (totalsnow(-0.00346, 1.73], holiday0)  (incident=1)   
45                         (totalsnow(-0.00346, 1.73])  (incident=1)   

     antecedent support  consequent support   support  confidence      lift  \
168            0.736318            0.694859  0.532338    0.722973  1.040460   
263            0.703151            0.694859  0.507463    0.721698  1.038625   
47             0.762852            0.694859  0.548922    0.719565  1.035556   
186            0.729685            0.694859  0.524046    0.718182  1.033565   
84             0.767828            0.694859  0.548922    0.714903  1.028846   
9              0.794362            0.694859  0.565506    0.711900  1.024524   
221            0.706468            0.694859  0.502488    0.711268  1.023614   
108            0.733002            0.694859  0.519071    0.708145  1.019120   
37             0.973466            0.694859  0.678275    0.696763  1.002740   
162            0.912106            0.694859  0.631841    0.692727  0.996932   
45             0.938640            0.694859  0.648425    0.690813  0.994177   

     leverage  conviction  
168  0.020701    1.101484  
263  0.018872    1.096439  
47   0.018847    1.088100  
186  0.017018    1.082758  
84   0.015390    1.070305  
9    0.013537    1.059149  
221  0.011592    1.056830  
108  0.009738    1.045522  
37   0.001854    1.006279  
162 -0.001944    0.993062  
45  -0.003798    0.986913

# AS WE ARE GETTING GOOD MODELS ON BINARY CLASFICATION ON FUTURE SCOPE WE CAN USE THIS FEATURES ON MULTI-CLASS CLASSIFICATION.



# Neural Network 

In [ ]:
# Importing all the essential libraries used for the Deep learning and neural Network

import pandas as pd
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import chi2
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from matplotlib import pyplot
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix

In [ ]:
#TRAIN DATA
dataset = pd.read_csv("traindata.csv")
#TEST DATA
dataset1= pd.read_csv("testdata.csv")


dataset=dataset.drop('cta_sites',axis=1)
dataset=dataset.drop('incident_date',axis=1)
dataset=dataset.drop('incident_time',axis=1)
dataset=dataset.drop('incident_category',axis=1)
dataset=dataset.drop('hours_after_sunrise',axis=1)
dataset=dataset.drop('hours_to_sunset',axis=1)
dataset=dataset.drop('week_day',axis=1)
dataset=dataset.drop('time_category',axis=1)
dataset=dataset.drop('weather_description',axis=1)

In [ ]:
dataset1=dataset1.drop('cta_sites',axis=1)
dataset1=dataset1.drop('incident_date',axis=1)
dataset1=dataset1.drop('incident_time',axis=1)
dataset1=dataset1.drop('incident_category',axis=1)
dataset1=dataset1.drop('hours_after_sunrise',axis=1)
dataset1=dataset1.drop('hours_to_sunset',axis=1)
dataset1=dataset1.drop('week_day',axis=1)
dataset1=dataset1.drop('time_category',axis=1)
dataset1=dataset1.drop('weather_description',axis=1)